sudo: false
language: bash
services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - LATEST=0.0.7

before_script:
  - env | sort
  - export IMAGE="claranet/project-bootstrap"
  - export VERSION="${TRAVIS_BRANCH:-${TRAVIS_TAG}}"

script:
  - docker build -t $IMAGE:$VERSION .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ -n "$LATEST" -a "$TRAVIS_TAG" == "$LATEST" ]; then
      docker tag $IMAGE:$VERSION $IMAGE:latest;
      docker push $IMAGE:$VERSION;
      docker push $IMAGE:latest;
    fi
